### ISSUE TITLE
Is Unity actually open-source?

### ISSUE THREAD

**Issue by linomp** [ertis-research/OpenTwins#3]
It would be useful to know exactly what role Unity plays in the system, and how coupled it is, to know where to draw a line in case a certain project requires exclusively open-source dependencies.  

Because it seems that the Unity engine is [source-available](https://github.com/Unity-Technologies/UnityCsReference), but [not open source](https://blog.unity.com/technology/releasing-the-unity-c-source-code).

**Comment by casafurix** [comment]
Hello @linomp , this might be unrelated, but I see you are talking about Unity, so were you able to successfully all the steps before using Unity for this project? I mean, setting up Kafka, InfluxDB etc, as mentioned in the README. Thanks! (I am facing errors that's why)

**Comment by linomp** [comment]
Hi @casafurix ;  no sorry, I haven't still tried this project in a hands-on way.   I was doing a survey of available Digital Twin tools for a project and that's why I came accross it.

**Comment by casafurix** [comment]
Ah, is it okay for you to share which project you are working on? I am currently working on a research project involving DT for a smart city application (wind turbine), and in process of devising an open-source solution for the same. Thanks!

**Comment by sergioinf** [comment]
Hi @linomp, as you said, Unity is not an open source project, but you can use it on personal and for education, as is our case.

The function of Unity in the platform is to give a graphical representation to the digital twins, either 3D, 2D, etc.

It is not really necessary for the operation of the platform. In fact, we do not have 3D models of all the twins we have developed, because some are simpler and we did not see the need for this representation.

So, if your project can only use opensource software you should look for another alternative for 3D rendering. The plugin we have developed allows the reproduction of Unity WebGL files, I do not guarantee that it will work, but it is possible that other files in WebGL format could be used as well.

P.D. Thanks @casafurix for your reply.
